FROM openjdk

WORKDIR /app

COPY ./ms-farm/target/farmbox-0.0.1-SNAPSHOT.jar /app/farmbox.jar

ENV SPRING_DATASOURCE_URL=jdbc:postgresql://envfarm:5432/farmbox

ENTRYPOINT ["java","-jar", "farmbox.jar"]

EXPOSE 8320

